module.exports = (sequelize, DataTypes) ->
  Host = sequelize.define('Host', {

    #
    hostname: DataTypes.STRING

    # 代理商品 or 精選商品
    # type: DataTypes.ENUM('AGENT', 'PRIME_GOOD', 'OTHER')

    #
    enable: DataTypes.BOOLEAN

    # 品牌介紹
    desc: DataTypes.TEXT

    # 順序權重
    weight: {
      type: DataTypes.INTEGER
      defaultValue: 0
    }

  },
  paranoid: true,
  classMethods: associate: (models) ->
    # Brand.belongsToMany(models.Brand, {through: 'BrandBook'});

    return
  )
  return Host

# ---
# generated by js2coffee 2.1.0
